/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-25 03:48:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("	.css-title{\n");
      out.write("		overflow: hidden;\n");
      out.write("		display: inline-block;\n");
      out.write("		font-weight: 700;\n");
      out.write("		color: rgb(47, 52, 56);\n");
      out.write("		letter-spacing: -0.3px;\n");
      out.write("		white-space: nowrap;\n");
      out.write("		text-overflow: ellipsis;\n");
      out.write("		font-size: 20px;\n");
      out.write("		line-height: 28px;\n");
      out.write("	}\n");
      out.write("	.today-special-price-headerBrand{display: block; font-size: 11px; color: #828c94;}\n");
      out.write("	.today-special-price-headerName{\n");
      out.write("		margin-top: 5px;\n");
      out.write("		font-size: 13px;\n");
      out.write("		font-weight: 400;\n");
      out.write("		line-height: 17px;\n");
      out.write("		max-height: 34px;\n");
      out.write("	}\n");
      out.write("	.today-special-price-itemPrice{\n");
      out.write("		display: flex;\n");
      out.write("		align-items: center;\n");
      out.write("		flex-wrap: wrap;\n");
      out.write("		font-size: 17px;\n");
      out.write("		line-height: 23px;\n");
      out.write("		font-weight: 700;\n");
      out.write("	}\n");
      out.write("	.item-star-review{margin-right: 2px; color: #424242; font-weight: 700;}\n");
      out.write("	.item-review-count{margin-top: 5px; font-size: 13px; color: #9e9e9e; line-height: 16px; font-weight: 700;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/top.jsp", out, false);
      out.write("\n");
      out.write("	</header>\n");
      out.write("	\n");
      out.write("	<main>\n");
      out.write("	<!-- 배너 -->\n");
      out.write("		<div id=\"myCarousel\" class=\"carousel carousel-dark slide\" data-bs-ride=\"carousel\">\n");
      out.write("			<div class=\"carousel-inner\">\n");
      out.write("				<div class=\"carousel-item active\">\n");
      out.write("					<img src=\"https://i.pinimg.com/originals/26/63/5b/26635bf988317b546ce1ef99f79d4f91.jpg\" style=\"width: 100%; height: 450px;\">\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"carousel-item\">\n");
      out.write("					<img src=\"https://openimage.interpark.com/dia/images/47/24/210506024/7dbda1c4398e4a93832fa454d911c835.jpg\" style=\"width: 100%; height: 450px;\">\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"carousel-item\">\n");
      out.write("					<img src=\"https://image.zdnet.co.kr/2018/03/13/hjan_nkih0Gcx16HCmbe.jpg\" style=\"width: 100%; height: 450px;\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide=\"prev\">\n");
      out.write("				<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("				<span class=\"visually-hidden\">Previous</span>\n");
      out.write("			</button>\n");
      out.write("			<button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide=\"next\">\n");
      out.write("				<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("				<span class=\"visually-hidden\">Next</span>\n");
      out.write("			</button>\n");
      out.write("		</div>\n");
      out.write("  		\n");
      out.write("  		<br><br>\n");
      out.write("  		\n");
      out.write("  		<!-- 오늘의 특가 상품 -->\n");
      out.write("  		<div class=\"container d-flex flex-wrap css-title\">\n");
      out.write("  			<div>\n");
      out.write("  				<div>\n");
      out.write("  					<div>\n");
      out.write("  						<strong class=\"p-4\">오늘의 특가 상품</strong>\n");
      out.write("  					</div>\n");
      out.write("  				</div>\n");
      out.write("  			</div>\n");
      out.write("  		</div>\n");
      out.write("  		\n");
      out.write("  		<div id=\"today_special_price\" class=\"carousel carousel-dark slide\" data-bs-ride=\"true\">\n");
      out.write("			<div class=\"carousel-inner\">\n");
      out.write("				<div class=\"carousel-item active\" data-bs-interval=\"10000\">\n");
      out.write("					<div class=\"album py-3\">\n");
      out.write("			  			<div class=\"container\">\n");
      out.write("			  				<div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3 p-2 px-4\">\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<img src=\"https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/166322024968332260.jpg?gif=1&w=850&h=850&c=c&webp=1\" style=\"width: 100%; height: 225px;\">\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					\n");
      out.write("			  				</div>\n");
      out.write("			  			</div>\n");
      out.write("			  		</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"carousel-item\">\n");
      out.write("					<div class=\"album py-3\">\n");
      out.write("			  			<div class=\"container\">\n");
      out.write("			  				<div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3 p-2 px-4\">\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					\n");
      out.write("			  				</div>\n");
      out.write("			  			</div>\n");
      out.write("			  		</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"carousel-item\">\n");
      out.write("					<div class=\"album py-3\">\n");
      out.write("			  			<div class=\"container\">\n");
      out.write("			  				<div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3 p-2 px-4\">\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col\">\n");
      out.write("			  						<div class=\"card shadow-sm\">\n");
      out.write("			  							<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\" height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  							</svg>\n");
      out.write("				  						<div class=\"card-body\">\n");
      out.write("				  							<span class=\"today-special-price-headerBrand\">STORE_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-headerName\">PRODUCT_NAME</span>\n");
      out.write("				  							<span class=\"today-special-price-itemPrice\">\n");
      out.write("				  								<span class=\"item-sale\">N</span>\n");
      out.write("				  								<span class=\"percentage\">% &nbsp;</span>\n");
      out.write("				  								<span class=\"item-price\">PRICE</span>\n");
      out.write("				  							</span>\n");
      out.write("				  							<div class=\"today-special-price-review\">\n");
      out.write("				  								<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" style=\"margin-bottom: 3px;\" fill=\"currentColor\" class=\"bi bi-star-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("				  									<path d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\"/>\n");
      out.write("												</svg>\n");
      out.write("				  								<span class=\"item-star-review\">4.8</span>\n");
      out.write("				  								<span class=\"item-review-count\">리뷰 500</span>\n");
      out.write("				  							</div>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					\n");
      out.write("			  				</div>\n");
      out.write("			  			</div>\n");
      out.write("			  		</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#today_special_price\" data-bs-slide=\"prev\">\n");
      out.write("				<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("				<span class=\"visually-hidden\">Previous</span>\n");
      out.write("			</button>\n");
      out.write("			<button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#today_special_price\" data-bs-slide=\"next\">\n");
      out.write("				<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("				<span class=\"visually-hidden\">Next</span>\n");
      out.write("			</button>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<br><br>\n");
      out.write("  		\n");
      out.write("  		<!-- 씽씽마켓 -->\n");
      out.write("  		<div class=\"container d-flex flex-wrap css-title\">\n");
      out.write("  			<div>\n");
      out.write("  				<div>\n");
      out.write("  					<div>\n");
      out.write("  						<strong class=\"p-4\">씽씽마켓</strong>\n");
      out.write("  					</div>\n");
      out.write("  				</div>\n");
      out.write("  			</div>\n");
      out.write("  		</div>\n");
      out.write("  		\n");
      out.write("  		<div id=\"ssingssing\" class=\"carousel carousel-dark slide\" data-bs-ride=\"true\">\n");
      out.write("			<div class=\"carousel-inner\">\n");
      out.write("				<div class=\"carousel-item active\" data-bs-interval=\"10000\">\n");
      out.write("					<div class=\"album\">\n");
      out.write("			  			<div class=\"container\">\n");
      out.write("			  				<div class=\"row px-4 mt-4\">\n");
      out.write("			  					<div class=\"col-md-6\">\n");
      out.write("			  						<div class=\"row g-0 border rounded overflow-hidden flex-md-row shadow-sm h-md-250 position-relative\">\n");
      out.write("			  							<div class=\"col p-4 d-flex flex-column position-static\">\n");
      out.write("			  								<h3 class=\"mb-0\">미니 가습기 판매해요</h3>\n");
      out.write("			  								<div class=\"mb-1\">20,000</div>\n");
      out.write("			  								<p class=\"card-text mb-auto\">사용감 없습니다</p>\n");
      out.write("			  							</div>\n");
      out.write("			  							<div class=\"col-auto d-none d-lg-block\">\n");
      out.write("			  								<svg class=\"bd-placeholder-img\" width=\"250\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  									<title>Placeholder</title>\n");
      out.write("			  									<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  									<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  								</svg>\n");
      out.write("			  							</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col-md-6\">\n");
      out.write("			  						<div class=\"row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\n");
      out.write("			  							<div class=\"col p-4 d-flex flex-column position-static\">\n");
      out.write("			  								<h3 class=\"mb-0\">Post title</h3>\n");
      out.write("			  								<div class=\"mb-1 text-muted\">Nov 11</div>\n");
      out.write("			  							</div>\n");
      out.write("				  						<div class=\"col-auto d-none d-lg-block\">\n");
      out.write("				  							<svg class=\"bd-placeholder-img\" width=\"250\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("				  								<title>Placeholder</title>\n");
      out.write("				  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("				  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("				  							</svg>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  				</div>\n");
      out.write("			  			</div>\n");
      out.write("			  		</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"carousel-item\">\n");
      out.write("					<div class=\"album py-3\">\n");
      out.write("			  			<div class=\"container\">\n");
      out.write("			  				<div class=\"row px-4 mt-4\">\n");
      out.write("			  					<div class=\"col-md-6\">\n");
      out.write("			  						<div class=\"row g-0 border rounded overflow-hidden flex-md-row shadow-sm h-md-250 position-relative\">\n");
      out.write("			  							<div class=\"col p-4 d-flex flex-column position-static\">\n");
      out.write("			  								<strong class=\"d-inline-block mb-2 text-primary\">World</strong>\n");
      out.write("			  								<h3 class=\"mb-0\">Featured post</h3>\n");
      out.write("			  								<div class=\"mb-1 text-muted\">Nov 12</div>\n");
      out.write("			  								<p class=\"card-text mb-auto\">This is a wider card with supporting text below as a natural lead-in to additional content.</p>\n");
      out.write("			  								<a href=\"#\" class=\"stretched-link\">Continue reading</a>\n");
      out.write("			  							</div>\n");
      out.write("			  							<div class=\"col-auto d-none d-lg-block\">\n");
      out.write("			  								<svg class=\"bd-placeholder-img\" width=\"200\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  									<title>Placeholder</title>\n");
      out.write("			  									<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  									<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  								</svg>\n");
      out.write("			  							</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col-md-6\">\n");
      out.write("			  						<div class=\"row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\n");
      out.write("			  							<div class=\"col p-4 d-flex flex-column position-static\">\n");
      out.write("			  								<strong class=\"d-inline-block mb-2 text-success\">Design</strong>\n");
      out.write("			  								<h3 class=\"mb-0\">Post title</h3>\n");
      out.write("			  								<div class=\"mb-1 text-muted\">Nov 11</div>\n");
      out.write("			  								<a href=\"#\" class=\"stretched-link\">Continue reading</a>\n");
      out.write("			  							</div>\n");
      out.write("				  						<div class=\"col-auto d-none d-lg-block\">\n");
      out.write("				  							<svg class=\"bd-placeholder-img\" width=\"200\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("				  								<title>Placeholder</title>\n");
      out.write("				  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("				  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("				  							</svg>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  				</div>\n");
      out.write("			  			</div>\n");
      out.write("			  		</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"carousel-item\">\n");
      out.write("					<div class=\"album py-3\">\n");
      out.write("			  			<div class=\"container\">\n");
      out.write("			  				<div class=\"row px-4 mt-4\">\n");
      out.write("			  					<div class=\"col-md-6\">\n");
      out.write("			  						<div class=\"row g-0 border rounded overflow-hidden flex-md-row shadow-sm h-md-250 position-relative\">\n");
      out.write("			  							<div class=\"col p-4 d-flex flex-column position-static\">\n");
      out.write("			  								<strong class=\"d-inline-block mb-2 text-primary\">World</strong>\n");
      out.write("			  								<h3 class=\"mb-0\">Featured post</h3>\n");
      out.write("			  								<div class=\"mb-1 text-muted\">Nov 12</div>\n");
      out.write("			  								<p class=\"card-text mb-auto\">This is a wider card with supporting text below as a natural lead-in to additional content.</p>\n");
      out.write("			  								<a href=\"#\" class=\"stretched-link\">Continue reading</a>\n");
      out.write("			  							</div>\n");
      out.write("			  							<div class=\"col-auto d-none d-lg-block\">\n");
      out.write("			  								<svg class=\"bd-placeholder-img\" width=\"200\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("			  									<title>Placeholder</title>\n");
      out.write("			  									<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("			  									<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  								</svg>\n");
      out.write("			  							</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  					\n");
      out.write("			  					<div class=\"col-md-6\">\n");
      out.write("			  						<div class=\"row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\n");
      out.write("			  							<div class=\"col p-4 d-flex flex-column position-static\">\n");
      out.write("			  								<strong class=\"d-inline-block mb-2 text-success\">Design</strong>\n");
      out.write("			  								<h3 class=\"mb-0\">Post title</h3>\n");
      out.write("			  								<div class=\"mb-1 text-muted\">Nov 11</div>\n");
      out.write("			  								<a href=\"#\" class=\"stretched-link\">Continue reading</a>\n");
      out.write("			  							</div>\n");
      out.write("				  						<div class=\"col-auto d-none d-lg-block\">\n");
      out.write("				  							<svg class=\"bd-placeholder-img\" width=\"200\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("				  								<title>Placeholder</title>\n");
      out.write("				  								<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("				  								<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("				  							</svg>\n");
      out.write("				  						</div>\n");
      out.write("			  						</div>\n");
      out.write("			  					</div>\n");
      out.write("			  				</div>\n");
      out.write("			  			</div>\n");
      out.write("			  		</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#ssingssing\" data-bs-slide=\"prev\">\n");
      out.write("				<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("				<span class=\"visually-hidden\">Previous</span>\n");
      out.write("			</button>\n");
      out.write("			<button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#ssingssing\" data-bs-slide=\"next\">\n");
      out.write("				<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("				<span class=\"visually-hidden\">Next</span>\n");
      out.write("			</button>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<br><br>\n");
      out.write("		\n");
      out.write("		<!-- 싱글벙글 -->\n");
      out.write("  		<div class=\"container d-flex flex-wrap css-title\">\n");
      out.write("  			<div>\n");
      out.write("  				<div>\n");
      out.write("  					<div>\n");
      out.write("  						<strong class=\"p-4\">싱글벙글</strong>\n");
      out.write("  					</div>\n");
      out.write("  				</div>\n");
      out.write("  			</div>\n");
      out.write("  		</div>\n");
      out.write("  		\n");
      out.write("  		<div class=\"container\">\n");
      out.write("  			<div class=\"row px-4 mt-4\">\n");
      out.write("			  	<div class=\"col-md-6\">\n");
      out.write("			  		<span style=\"margin: 10px;\">- HOT 인기글</span>\n");
      out.write("			  		<div class=\"row g-0 border rounded overflow-hidden flex-md-row shadow-sm h-md-250 position-relative\">\n");
      out.write("			  			<div class=\"col-auto d-none d-lg-block\">\n");
      out.write("			  				<svg class=\"bd-placeholder-img\" width=\"250\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("				  				<title>Placeholder</title>\n");
      out.write("				  				<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("				  				<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("			  				</svg>\n");
      out.write("			  			</div>\n");
      out.write("			  			<div class=\"col p-4 d-flex flex-column position-static\">\n");
      out.write("			  				<strong class=\"d-inline-block mb-2 text-primary\">World</strong>\n");
      out.write("			  				<h3 class=\"mb-0\">Featured post</h3>\n");
      out.write("			  				<div class=\"mb-1 text-muted\">Nov 12</div>\n");
      out.write("			  				<p class=\"card-text mb-auto\">This is a wider card with supporting text below as a natural lead-in to additional content.</p>\n");
      out.write("			  				<a href=\"#\" class=\"stretched-link\">Continue reading</a>\n");
      out.write("			  			</div>\n");
      out.write("			  		</div>\n");
      out.write("			  	</div>\n");
      out.write("			  	\n");
      out.write("			  	\n");
      out.write("			  	<div class=\"col-md-6\">\n");
      out.write("			  		<span style=\"margin: 10px;\">- HOT 판매자 인기글</span>\n");
      out.write("			  		<div class=\"row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\n");
      out.write("			  			<div class=\"col-auto d-none d-lg-block\">\n");
      out.write("				  			<svg class=\"bd-placeholder-img\" width=\"250\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\n");
      out.write("				  				<title>Placeholder</title>\n");
      out.write("				  				<rect width=\"100%\" height=\"100%\" fill=\"#55595c\"/>\n");
      out.write("				  				<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text>\n");
      out.write("				  			</svg>\n");
      out.write("				  		</div>\n");
      out.write("			  			<div class=\"col p-4 d-flex flex-column position-static\">\n");
      out.write("			  				<strong class=\"d-inline-block mb-2 text-success\">Design</strong>\n");
      out.write("			  				<h3 class=\"mb-0\">Post title</h3>\n");
      out.write("			  				<div class=\"mb-1 text-muted\">Nov 11</div>\n");
      out.write("			  				<a href=\"#\" class=\"stretched-link\">Continue reading</a>\n");
      out.write("			  			</div>\n");
      out.write("			  		</div>\n");
      out.write("			  	</div>\n");
      out.write("			</div>\n");
      out.write("  		</div>\n");
      out.write("	</main>\n");
      out.write("	\n");
      out.write("	<footer>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/footer.jsp", out, false);
      out.write("\n");
      out.write("	</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
